#!/usr/bin/env ruby

require 'fileutils'
include FileUtils


if ARGV[0] =~ /t/
  rm_rf "/tmp/partition-big-dirs-test/"

  for dir in [1,2,3,22,23,24,333,1000,3334,4444,55555,666666,7777777,88888888,999999999]
    mkpath "/tmp/partition-big-dirs-test/#{dir}"
    touch  "/tmp/partition-big-dirs-test/#{dir}/foo-#{dir}.jpg"
  end

else
  Dir.new('.').each do |dir|
    unless dir =~ /\D/
      if File.directory?(dir)
        new = ("%08d" % dir).scan(/\d{4}/).join("/")
        puts new
        mkpath(File::dirname(new))
        mv dir, new
      end
    end
  end
end
