#!/bin/sh

# Usage:
#   tmux-rails
#   tmux-rails directory-with-project-in-it

if [ $# -eq 1 ]
then
    if [ -d $1 ]
    then
	cd $1
    else
	echo "directory $1 not found"
	exit 1
    fi
fi

PROJECT=`basename $PWD`
PORT=`ruby -e 'puts (ARGV[0][0].upcase.ord - 65) + (ARGV[0][-1].upcase.ord - 65) * 100 + 3000' $PROJECT`

tmux start-server

if tmux has-session -t $PROJECT 2>/dev/null
then
    tmux attach -t $PROJECT
else
    tmux new-session -s $PROJECT -d -n server
    tmux send-keys   -t $PROJECT:0 "rails s -p $PORT" C-m

    tmux new-window  -t $PROJECT -n emacs
    tmux send-keys   -t $PROJECT:1 "TERM=xterm-256color emacs" C-m

    tmux new-window  -t $PROJECT -n shell
   #tmux send-keys   -t $PROJECT:2 C-l

    tmux new-window  -t $PROJECT -n console
    tmux send-keys   -t $PROJECT:3 "cd .; rails c" C-m

    tmux new-window  -t $PROJECT -n db
    tmux send-keys   -t $PROJECT:4 "cd .; rails db" C-m

    tmux select-window  -t $PROJECT:2
    tmux attach-session -t $PROJECT
fi


